### ISSUE TITLE
"Add 60 Seconds To Mission Timer" cheat is not working.

### ISSUE THREAD

**Issue by sadmemesosad** [bad1dea/NXCheats#125] opened 2023-06-08 20:22 UTC
Pressing two analog buttons at the same time won't solve it. 

I've tried several times, 
and I've tried changing the key mapping, but it doesn't work.

I'm a person who can't control quickly in the game, 
so I find it very difficult to do missions in time-limited situations.

Please give me a hand.

**Comment by bad1dea** [comment] 2023-06-08 21:15
1) Paste the cheats you have activated (exact ones on your switch)
2) Switch or Emu?
3) What buttons are you pressing exactly?

I created the code for this purpose.. I've just retested it.. and it's working as programmed.

**Comment by sadmemesosad** [comment] 2023-06-09 00:58
> 

1. I tried it once as you mentioned, but it doesn't seem to work.
2. YUZU Mainline lastest
3. Isn't L3+R3 to click left and right analog sticks at the same time?
4. While searching, it seems that there is already someone who asked the same question before. 
As you mentioned, it doesn't seem to work on an emulator.

**Comment by bad1dea** [comment] 2023-06-09 16:35
Duplicate of #121

**Closed by bad1dea** 2023-06-09 16:35 UTC

**Comment by sadmemesosad** [comment] 2023-06-09 23:17
> Duplicate of #121

I have the same problem. The moment you open the item menu window, the game stops.
