### ISSUE TITLE
Zelda TOTK Item Multiplier Cause Blueprint Blank

### ISSUE THREAD

**Issue by icyomik** [bad1dea/NXCheats#35] opened 2023-05-10 06:29 UTC
Hello, cheats works very well, but currently found a problem, "Item Pickup/Sell/Buy Multiplier" will cause the blueprint's history to be blank in the middle, if I set 5 times, then there will be 4 blank in two blueprint's records. If it is convenient, please help to fix it, thank you.
Additional, the file path is: 
bad1dea/NXCheats/The Legend of Zelda Tears of the Kingdom/The Legend of Zelda Tears of the Kingdom (US)/0100F2C0115B6000/cheats/D5AD6AC71EF53E3E.txt

**Comment by damianb** [comment] 2023-05-10 15:06
Related/duplicate of #28, I think.

**Comment by bad1dea** [comment] 2023-05-11 23:14
Please send save file and description of how to duplicate error/bug.

**Closed** 2023-05-16 01:15 UTC
